### ISSUE TITLE
Enhancement Request: Implement HTTP/2 for Portal

### ISSUE THREAD

**Issue by cqueern** [tridentli/pitchfork#177]
Background: https://www.nginx.com/blog/http2-theory-and-practice-in-nginx-stable-13/

Recommend that web server config be modified to serve http requests over HTTP/2 by default for better performance for users. Should be a pretty easy upgrade with nginx.

**Comment by massar** [comment]
While we have:
https://github.com/tridentli/trident/blob/master/doc/conf/nginx/trident-server.inc

Currently there is no 'listener' definition. It is thus up to the install to determine these parameters.

As per nginx, simply having:
```
server {
       listen 443 ssl http2;
       listen [::]:443 ssl http2;
```

will make a site HTTP/2 enabled.
