### ISSUE TITLE
Remove support for TLS 1.0 and 1.1

### ISSUE THREAD

**Issue by cqueern** [tridentli/pitchfork#179]
It looks like the Portal currently supports 1.0, 1.1 and 1.2. 

We can probably get by with TLS 1.2 alone with no impact to users.

Suggest we remove support for TLS 1.0 and 1.1. Thanks!

**Comment by massar** [comment]
TLS versions are determined by the configuration of the server and thus how the operator configures it.

The configuration included in trident does not configure it.

We can suggest using the Mozilla TLS generator:
https://mozilla.github.io/server-side-tls/ssl-config-generator/

**Comment by morrowc** [comment]
I think caleb's question is: "can you make the actual live portal do this?"
which I think: "yes".

At Sun, 31 Mar 2019 07:15:43 -0700,

**Comment by massar** [comment]
trident hat:
```
Nginx can do it, thus indeed yes. But it is up to the individual sites to deploy that.
Out of scope of either trident/pitchfork to determine those parameters.
```

ops-t sysadmin hat
```
for ops-t, requests should be put in the special RT queues.
```
Those requests do not belong in an open forum...

**Comment by morrowc** [comment]
On Tue, 02 Apr 2019 07:17:29 -0400,
Jeroen Massar <notifications@github.com> wrote:
> 
> [1  <text/plain; UTF-8 (7bit)>]
> trident hat:
> ```
> Nginx can do it, thus indeed yes. But it is up to the individual sites to deploy that.
> Out of scope of either trident/pitchfork to determine those parameters.
> ```
> 
> ops-t sysadmin hat
> ```
> for ops-t, requests should be put in the special RT queues.
> ```
> Those requests do not belong in an open forum...

totally agree.
